### ISSUE TITLE
Do we really need pip here?

### ISSUE THREAD

**Issue by IAmScRay** [vana-com/vana-dlp-chatgpt#38]
Do we really need to use pip [here](https://github.com/vana-com/vana-dlp-chatgpt/blob/main/docs/running_on_testnet.md#setup-vanacli)?

I have installed dependencies via `poetry`, and when trying `pip` it errors a lot:
```
Building wheels for collected packages: ansible-vault, pyunormalize
  Building wheel for ansible-vault (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for ansible-vault (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [72 lines of output]
      /usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/ansible_vault
      copying ansible_vault/__init__.py -> build/lib/ansible_vault
      copying ansible_vault/_compat.py -> build/lib/ansible_vault
      copying ansible_vault/api.py -> build/lib/ansible_vault
      copying ansible_vault/parsing.py -> build/lib/ansible_vault
      running install
      running install_lib
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 230, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 268, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 11, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 335, in run
          self.run_command('install')
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/install.py", line 622, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 985, in run_command
          cmd_obj.ensure_finalized()
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 107, in ensure_finalized
          self.finalize_options()
        File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 17, in finalize_options
          self.set_undefined_options('install',('install_layout','install_layout'))
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 290, in set_undefined_options
          setattr(self, dst_option, getattr(src_cmd_obj, src_option))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 103, in __getattr__
          raise AttributeError(attr)
      AttributeError: install_layout. Did you mean: 'install_platlib'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ansible-vault
  Building wheel for pyunormalize (setup.py) ... done
  Created wheel for pyunormalize: filename=pyunormalize-15.1.0-py3-none-any.whl size=516046 sha256=a243ef93eaef728c16ff38af2cd655ab4b75a0f4d991048c90b231fb6e378ae1
  Stored in directory: /home/vana/.cache/pip/wheels/07/4e/a1/96ad639a4f1f708e8ccf733b63783ef98e994b1c0e54599ca2
Successfully built pyunormalize
Failed to build ansible-vault
ERROR: Could not build wheels for ansible-vault, which is required to install pyproject.toml-based projects
```

Since we've installed `vana` dependency [here](https://github.com/vana-com/vana-dlp-chatgpt/blob/main/pyproject.toml#L17), I suggest the team corrects the guide & gets rid of the `pip` instructions.

**Comment by Kahtaf** [comment]
Thanks for reporting! The reason we ask users to `pip install vana` is to ensure `vanacli` is available system-wide. 

Perhaps we need to make it clear in the README that this is optional.

**Comment by IAmScRay** [comment]
That addition to the README would be much appreciated!💪
