### ISSUE TITLE
ProviderError: tx fee (1.11 ether) exceeds the configured cap (1.00 ether)

### ISSUE THREAD

**Issue by fl77ex** [vana-com/vana-dlp-chatgpt#68]
root@1:~/vana-dlp-smart-contracts# npx hardhat deploy --network satori --tags DLPDeploy
WARNING: You are currently using Node.js v22.9.0, which is not supported by Hardhat. This can lead to unexpected behavior. See https://hardhat.org/nodejs-versions

Nothing to compile
No need to generate any newer typings.
An unexpected error occurred:

Error: ERROR processing /root/vana-dlp-smart-contracts/deploy/dlp-deploy.ts:
ProviderError: tx fee (1.11 ether) exceeds the configured cap (1.00 ether)
    at HttpProvider.request (/root/vana-dlp-smart-contracts/node_modules/hardhat/src/internal/core/providers/http.ts:90:21)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async HardhatEthersSigner.sendTransaction (/root/vana-dlp-smart-contracts/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async ContractFactory.deploy (/root/vana-dlp-smart-contracts/node_modules/ethers/src.ts/contract/factory.ts:111:24)
    at async Object.func (/root/vana-dlp-smart-contracts/deploy/dlp-deploy.ts:17:21)
    at async DeploymentsManager.executeDeployScripts (/root/vana-dlp-smart-contracts/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1211:22)
    at async DeploymentsManager.runDeploy (/root/vana-dlp-smart-contracts/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1060:5)
    at async SimpleTaskDefinition.action (/root/vana-dlp-smart-contracts/node_modules/hardhat-deploy/src/index.ts:450:5)
    at async Environment._runTaskDefinition (/root/vana-dlp-smart-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:359:14)
    at async Environment.run (/root/vana-dlp-smart-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:192:14)
    at DeploymentsManager.executeDeployScripts (/root/vana-dlp-smart-contracts/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1214:19)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async DeploymentsManager.runDeploy (/root/vana-dlp-smart-contracts/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1060:5)
    at async SimpleTaskDefinition.action (/root/vana-dlp-smart-contracts/node_modules/hardhat-deploy/src/index.ts:450:5)
    at async Environment._runTaskDefinition (/root/vana-dlp-smart-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:359:14)
    at async Environment.run (/root/vana-dlp-smart-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:192:14)
    at async SimpleTaskDefinition.action (/root/vana-dlp-smart-contracts/node_modules/hardhat-deploy/src/index.ts:601:32)
    at async Environment._runTaskDefinition (/root/vana-dlp-smart-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:359:14)
    at async Environment.run (/root/vana-dlp-smart-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:192:14)
    at async SimpleTaskDefinition.action (/root/vana-dlp-smart-contracts/node_modules/hardhat-deploy/src/index.ts:690:5)

**Comment by kionlife** [comment]
Any solution? I have the same error

**Comment by fl77ex** [comment]
> Any solution? I have the same error

yep. switch to moksha new testnet

**Comment by kionlife** [comment]
> > Any solution? I have the same error
> 
> yep. switch to moksha new testnet

Can you tell me link for new?

**Comment by fl77ex** [comment]
> > > Any solution? I have the same error
> > 
> > 
> > yep. switch to moksha new testnet
> 
> Can you tell me link for new?

you need to deploy in moksha testnet. try this: 
https://teletype.in/@thegentlemen/guide_na_nodu_VANA
